<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reports Summary</title>
    <style>
        body {
            font-family: DejaVu Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            font-size: 12px;
            color: #111827;
            margin: 24px;
        }
        h1 {
            font-size: 20px;
            margin-bottom: 4px;
        }
        .subtitle {
            font-size: 11px;
            color: #6B7280;
            margin-bottom: 16px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }
        th, td {
            border: 1px solid #E5E7EB;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #F3F4F6;
            font-weight: 600;
        }
        .text-right {
            text-align: right;
        }
        .header {
            display: table;
            width: 100%;
            margin-bottom: 12px;
        }
        .header-left,
        .header-right {
            display: table-cell;
            vertical-align: top;
        }
        .header-right {
            text-align: right;
            font-size: 11px;
            color: #374151;
        }
        .business-name {
            font-weight: 600;
            font-size: 13px;
            margin-bottom: 2px;
        }
        .business-line {
            margin: 1px 0;
        }
        .divider {
            height: 2px;
            background-color: #2563EB;
            margin: 8px 0 16px 0;
        }
        .footer {
            margin-top: 24px;
            text-align: center;
            font-size: 10px;
            color: #9CA3AF;
        }
    </style>
</head>
<body>
    @php
        /** @var \App\Models\Setting|null $settings */
        $settings = \App\Models\Setting::getSettings();
    @endphp

    <div class="header">
        <div class="header-left">
            <img src="{{ public_path('images/logo.png') }}" alt="InvoiceGo" style="height:40px;">
        </div>
        <div class="header-right">
            <div class="business-name">
                {{ $settings->business_name ?? 'InvoiceGo' }}
            </div>
            <div class="business-line">
                GSTIN: {{ $settings->gst_number ?? '-' }}
            </div>
            <div class="business-line">
                Phone: {{ $settings->phone ?? '-' }}
            </div>
            <div class="business-line">
                Email: {{ $settings->email ?? '-' }}
            </div>
        </div>
    </div>

    <div class="divider"></div>

    <h1>Reports Summary</h1>
    <div class="subtitle">
        Generated on {{ now()->format('d M Y, H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th class="text-right">Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total Revenue</td>
                <td class="text-right">
                    ₹{{ number_format((float) ($summary['total_revenue'] ?? 0), 2) }}
                </td>
            </tr>
            <tr>
                <td>GST Collected</td>
                <td class="text-right">
                    ₹{{ number_format((float) ($summary['gst_collected'] ?? 0), 2) }}
                </td>
            </tr>
            <tr>
                <td>Subtotal (Before GST)</td>
                <td class="text-right">
                    ₹{{ number_format((float) ($summary['subtotal_sum'] ?? 0), 2) }}
                </td>
            </tr>
            <tr>
                <td>Total Invoices</td>
                <td class="text-right">
                    {{ (int) ($summary['total_invoices'] ?? 0) }}
                </td>
            </tr>
            <tr>
                <td>Paid Invoices</td>
                <td class="text-right">
                    {{ (int) ($summary['paid_count'] ?? 0) }}
                </td>
            </tr>
            <tr>
                <td>Pending Invoices</td>
                <td class="text-right">
                    {{ (int) ($summary['pending_count'] ?? 0) }}
                </td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by InvoiceGo &bull; sirfstyle.in
    </div>
</body>
</html>

